- name: Register a Variable
  hosts: localhost
  tasks:
    - name: get uptime output
      ansible.builtin.shell: uptime
      register: out
    
    - name: print the out
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Declare a Variable
      ansible.builtin.set_fact:
        status: "{{ out.rc }}"

    - name: print the out.rc
      ansible.builtin.debug:
        msg: "{{ status }}"