- name: Play Variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Play Variables From Files
  hosts: localhost
  vars_files:
    - var.yml
  tasks:
    - name: Print Play Variable From File
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Task Variables
  hosts: localhost
  tasks:
    - name: Print Task Variable
      vars:
        URL: task.example.com
      ansible.builtin.debug:
        msg: URL = {{ URL }}    

- name: Inventry Variables
  hosts: localhost
  tasks:
    - name: Print Play Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}    